import type { Metadata } from 'next';
import './globals.css';
// import Nav from '@/components/Nav';

export const metadata: Metadata = {
  title: 'Unified Coding Challenge',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className='bg-slate-100 text-gray-900'>
        <div className='container mx-auto relative py-5'>
          {children}
        </div>
      </body>
    </html>
  );
}
